import openai
import os
import requests
from PIL import Image

def generate_image(text):
    """
    Uses OpenAI API to request an image to be generated by their DallE model.

    :param text: text prompt for OpenAI image generation
    :return: URL to the image or None if failed
    """
    res = openai.Image.create(
        prompt=text,
        n=1,
        size="256x256",
    )
    if "data" not in res:
        return None
    return res["data"][0]["url"]

openai.api_key = os.getenv("OPENAI_API_KEY")
text = input("What image you would like me to generate? ")
url = generate_image(text)
if url:
    im = Image.open(requests.get(url, stream=True).raw)
    im.show()
